Feature/vdyp 400 grow qmd+lh
bcgov/NR-VDYP pull request #60
Opened 2024-09-04 18:18 UTC by mjunkin

Implementation complete and unit testing completed up to step 6 of grow().

2024-09-09 22:26 UTC, smithkm requested changes

2024-09-09 22:30 UTC, smithkm commented
The comments about magic numbers and unifying some methods in UtilizationOperations are more thoughts I had while reviewing.  They might make more sense to deal with more comprehensively across the code base instead of in this PR.  the DQ magic number is also a bit annoying since there are so many slightly offset versions of it, should we make a constant for each or offset each from the base as it's used?

2024-09-10 00:00 UTC, mjunkin commented on vdyp-lib/vdyp-forward/src/main/java/ca/bc/gov/nrs/vdyp/forward/ForwardProcessingEngine.java
> +				tryTph[i] = BaseAreaTreeDensityDiameter.treesPerHectare(baNew[i], tryDq[i]);
Agreed. I've changed uses of the UC constants to lowBound and highBound of the UC enum values. I have not changed comments referring to them, or any of the tests.

2024-09-10 00:12 UTC, mjunkin commented on vdyp-lib/vdyp-forward/src/main/java/ca/bc/gov/nrs/vdyp/forward/ForwardProcessingEngine.java
> +		float primaryF = (pspLhStart - 1.3f) / (pspLhStartEstimate - 1.3f);
I think it's "breast height" but there are other constants around that value also used. So I'm not really sure how best to handle this and it's out of the scope of these changes anyway, so it'll have to wait.

2024-09-10 00:13 UTC, mjunkin commented on vdyp-lib/vdyp-forward/src/main/java/ca/bc/gov/nrs/vdyp/forward/ForwardProcessingEngine.java
> +			if (equationModifierGroup.isPresent()) {
Agreed...

2024-09-10 00:15 UTC, mjunkin commented on vdyp-lib/vdyp-forward/src/main/java/ca/bc/gov/nrs/vdyp/forward/LambdaProcessingException.java
I wasn't aware of RuntimeProcessingException. I'll remove Lambda and use it.

2024-09-10 00:18 UTC, mjunkin commented on vdyp-lib/vdyp-forward/src/main/java/ca/bc/gov/nrs/vdyp/forward/UtilizationOperations.java
> +
Agreed, added TODO to UtilizationOperations.

2024-09-10 00:21 UTC, mjunkin commented on vdyp-lib/vdyp-forward/src/main/java/ca/bc/gov/nrs/vdyp/forward/UtilizationOperations.java
> +	private static final UtilizationVector CLASS_LOWER_BOUNDS = new UtilizationVector(
Yes, I momentarily forgot that...

2024-09-10 00:25 UTC, mjunkin commented on vdyp-lib/vdyp-forward/src/test/java/ca/bc/gov/nrs/vdyp/forward/CalculateQuadMeanDiameterDeltaTest.java
> +		assertTrue(dqGrowthLimitApplied.isPresent());
This isn't an Optional.

2024-09-10 17:31 UTC, mjunkin commented on vdyp-lib/vdyp-forward/src/test/java/ca/bc/gov/nrs/vdyp/forward/ForwardProcessorTest.java
Seems best to leave it as is for now.

2024-09-10 17:31 UTC, mjunkin commented on vdyp-lib/vdyp-forward/src/test/java/ca/bc/gov/nrs/vdyp/forward/ForwardProcessorTest.java
> +			Files.delete(zipFilePath);
OK, done.

2024-09-10 17:31 UTC, mjunkin commented on vdyp-lib/vdyp-common/src/test/java/ca/bc/gov/nrs/vdyp/io/ZipOutputFileResolverTest.java
OK, done.

2024-09-10 18:56 UTC, smithkm approved these changes

2024-09-10 19:26 UTC, merged