Update Client Library and API Integration for Backend Changes
bcgov/nr-vdyp pull request #92
Opened 2024-12-11 21:54 UTC by vividroyjeong

- Update client library and API integration to match backend changes
- Re-config proxy for base path(start with '/api') change in backend api

2024-12-11 23:31 UTC, dhlevi requested changes
We shouldn't be disabling ts/es linting. If you're seeing errors popping up, try to correct them appropriately vs. disabling the rules.

Couple questions on the parameter factories around the use of async/promises. If they're required, no worries, just wasn't sure what the purpose of them was.

2024-12-11 23:31 UTC, dhlevi commented on frontend/src/services/vdyp-api/apis/run-dcsvprojection-api.ts
> +/* tslint:disable */
We shouldn't be disabling tslint. If you're getting linting errors, it's better to correct them vs. disabling the checks.

Note that Sonar will check them anyway and they'll need to be corrected regardless.

2024-12-11 23:31 UTC, dhlevi commented on frontend/src/services/vdyp-api/apis/run-dcsvprojection-api.ts
> +    projectionDcsvPostForm: async (
Why is this async? It includes a promise I'm just not sure why?

2024-12-11 23:31 UTC, dhlevi commented on frontend/src/services/vdyp-api/apis/run-dcsvprojection-api.ts
> +    projectionDcsvPostForm: async (
I see the axios config, I just don't see it getting executed

2024-12-11 23:31 UTC, dhlevi commented on frontend/src/services/vdyp-api/apis/run-dcsvprojection-api.ts
> +    projectionDcsvPostForm: async (
Is it only for the factory function below?

2024-12-11 23:31 UTC, dhlevi commented on frontend/src/services/vdyp-api/apis/run-hcsvprojection-api.ts
> +export const RunHCSVProjectionApiAxiosParamCreator = function (
Same as previous comment, should this be a promise? Doesn't seem to execute anything in an async way

2024-12-11 23:31 UTC, dhlevi commented on frontend/src/services/vdyp-api/apis/run-hcsvprojection-api.ts
> +/* tslint:disable */
As above, do not disable tslint/eslint

2024-12-11 23:31 UTC, dhlevi commented on frontend/src/services/vdyp-api/apis/run-scsvprojection-api.ts
> +/* tslint:disable */
As above, do not disable tslint/eslint

2024-12-11 23:31 UTC, dhlevi commented on frontend/src/services/vdyp-api/apis/run-scsvprojection-api.ts
> +      const localVarHeaderParameter = {} as any
Ideally we don't use `any`. We should define a type for this if possible.

2024-12-12 17:26 UTC, vividroyjeong commented
@dhlevi Thank you for your last review. I've made the following changes to address your concerns. Please review again.
- Remove tslint/eslint disabling
- Remove unused dcsvprojection/scsvprojection api client libraries 
  : Remove csvprojection/scsvprojection api client libraries, which was causing issues with using async/promises. Currently it is not 
    being used, it is only declared in the API, not implemented. The client library was generated incorrectly. I've removed it to avoid 
    confusion. If it is implemented in the API in the future and we need it, I'll create it accordingly.
- Clean up - Remove unnecessary comments and unused import class

2024-12-12 19:55 UTC, dhlevi approved these changes

2024-12-12 22:41 UTC, merged